Добавление возможности голосовать за вопросы/ответы
GolovkoStepan/qna_rails pull request #7
Opened 2021-02-05 13:39 UTC by GolovkoStepan

2021-02-06 08:49 UTC, vkurennov requested changes

2021-02-06 08:49 UTC, vkurennov commented on app/controllers/concerns/opportunity_to_vote.rb
> +    skip_before_action :authenticate_user!, only: %i[vote_plus vote_minus]
почему skip? голосовать разве может незалогиненный юзер?

2021-02-06 08:49 UTC, vkurennov commented on app/controllers/concerns/opportunity_to_vote.rb
> +    return not_authorized_response unless current_user
это бы не понадобилось, если не скипать аутентификацию

2021-02-06 08:49 UTC, vkurennov commented on app/controllers/concerns/opportunity_to_vote.rb
> +    render json: { status: 'internalError', message: error.message }
ну если ошибку возвращаешь, то и статус надо вернуть соответсвующий (в данном случае - 500й), правда, если исключение не обрабатывать, то в прод-режиме и так вернется 500я ошибка на любое исключение

2021-02-06 08:49 UTC, vkurennov commented on app/models/concerns/has_votes.rb
> +    if (vote = votes.find_by(user: user))
скобки тут не нужны

2021-02-06 08:49 UTC, vkurennov commented on app/models/concerns/has_votes.rb
> +  rescue ActiveRecord::RecordInvalid
ну тогда можно в методе vote! просто использовать не-bang версии методов и не понадобится этот. но если это имеет смысл, то ок

2021-02-06 08:49 UTC, vkurennov commented on app/models/concerns/has_votes.rb
> +module HasVotes
а где тесты моделей на этот консерн? эти методы тоже надо протестировать

2021-02-06 08:55 UTC, GolovkoStepan commented on app/controllers/concerns/opportunity_to_vote.rb
> +    skip_before_action :authenticate_user!, only: %i[vote_plus vote_minus]
нет, проверка авторизации будет в экшене

2021-02-06 08:59 UTC, GolovkoStepan commented on app/controllers/concerns/opportunity_to_vote.rb
> +    return not_authorized_response unless current_user
согласен) но я хотел, чтобы всегда приходило 200 с json, а уже по полю status мы будем понимать как завершился запрос (ну, типа вместо обработки HTTP статусов):
ok - если все норм
internalError - если были ошибки на сервере
notAllowed - если голосуем за свое
notAuthorized - если не авторизован

2021-02-06 09:00 UTC, GolovkoStepan commented on app/controllers/concerns/opportunity_to_vote.rb
> +    render json: { status: 'internalError', message: error.message }
ну тут вроде как любые ошибки перехватятся, по поводу статусов выше дал ответ

2021-02-06 09:02 UTC, GolovkoStepan commented on app/models/concerns/has_votes.rb
> +  rescue ActiveRecord::RecordInvalid
ага, просто так с виду было бы дублирование кода, решил вот так сделать

2021-02-06 09:02 UTC, GolovkoStepan commented on app/models/concerns/has_votes.rb
> +module HasVotes
сори, забыл, добавлю

2021-02-06 09:02 UTC, GolovkoStepan commented on app/models/concerns/has_votes.rb
> +    if (vote = votes.find_by(user: user))
ок)

2021-02-07 08:26 UTC, GolovkoStepan commented on app/models/concerns/has_votes.rb
> +    if (vote = votes.find_by(user: user))
rubymine отвечает на это "Assignment expression in conditional"

2021-02-07 12:22 UTC, merged